In [46]:
# Importing Required library
import joblib
import logging
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
from sklearn.linear_model import LinearRegression

In [53]:
class predictModel:
    logging.basicConfig(filename='model.log', level=logging.DEBUG, format='%(asctime)s %(levelname)s %(message)s')
    def pandasProfiling(self,dataFrame):
        self.dataFrame = dataFrame
        pf = ProfileReport(dataFrame)
        pf.to_widgets()
        logging.info("Pandas Profiling Done...")
    def myAnalysis(self):
        logging.info('My Analysis of Data( AI4I 2020 Predictive Maintenance)')

        logging.info('There is 14 number of attributes in my dataset which consist many funtionality [inner or outter] of machine.There is 5 inner funtionality which is highly correlated to Machine failure.\nIf any funtionality among these 5 are failed, then Machine will failed definetly.\nThis dataset also consist type of machine i.e. High, Medium and Low which indicated the product quality.\nOur task is to find out, on certain point or consist certain output of these factor [Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF], what is the air temperature will it have.')
        
    def gettingIndependentAndDependentFeatures(self, dataFrame):
        self.dataFrame = dataFrame
        self.x =  self.dataFrame[['Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]','Machine failure','TWF','HDF','PWF','OSF','RNF']]
        self.y = self.dataFrame[['Air temperature [K]']]
        logging.info('Independent and Dependent Feature is created.. ')
        return self.x
    def createModel(self, dataFrame):
        self.linear = LinearRegression()
        (self.linear).fit(self.x,self.y)
        logging.info(str((self.linear).fit(self.x,self.y))+' Model Object is created....')
    def testModel(self,independentData):
        logging.info('Model Testing '+str((self.linear).predict([independentData])))
    def modelAccuracy(self):
        logging.info('Model Accuracy '+str((self.linear).score(self.x,self.y)))

In [54]:
modelObj = predictModel()
df = pd.read_csv('ai4i2020.csv')
# modelObj.pandasProfiling(df)
modelObj.myAnalysis()
modelObj.gettingIndependentAndDependentFeatures(df)
modelObj.createModel(df)
modelObj.testModel([309.5,1294,66.7,12,1,0,0,1,0,0])
modelObj.modelAccuracy()

In [12]:
df

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6   
1         2     L47181    L                298.2                    308.7   
2         3     L47182    L                298.1                    308.5   
3         4     L47183    L                298.2                    308.6   
4         5     L47184    L                298.2                    308.7   
...     ...        ...  ...                  ...                      ...   
9995   9996     M24855    M                298.8                    308.4   
9996   9997     H39410    H                298.9                    308.4   
9997   9998     M24857    M                299.0                    308.6   
9998   9999     H39412    H                299.0                    308.7   
9999  10000     M24859    M                299.0                    308.7   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                       1551         42.8                0                0   
1                       1408         46.3                3                0   
2                       1498         49.4                5                0   
3                       1433         39.5                7                0   
4                       1408         40.0                9                0   
...                      ...          ...              ...              ...   
9995                    1604         29.5               14                0   
9996                    1632         31.8               17                0   
9997                    1645         33.4               22                0   
9998                    1408         48.5               25                0   
9999                    1500         40.2               30                0   

      TWF  HDF  PWF  OSF  RNF  
0       0    0    0    0    0  
1       0    0    0    0    0  
2       0    0    0    0    0  
3       0    0    0    0    0  
4       0    0    0    0    0  
...   ...  ...  ...  ...  ...  
9995    0    0    0    0    0  
9996    0    0    0    0    0  
9997    0    0    0    0    0  
9998    0    0    0    0    0  
9999    0    0    0    0    0  

[10000 rows x 14 columns]

In [14]:
# My Analysis of Data( AI4I 2020 Predictive Maintenance)

# There is 14 number of attributes in my dataset which consist many funtionality [inner or outter] of machine.
# There is 5 inner funtionality which is highly correlated to Machine failure.
# If any funtionality among these 5 are failed, then Machine will failed definetly.
# This dataset also consist type of machine i.e. High, Medium and Low which indicated the product quality.
# Our task is to find out, on certain point or consist certain output of these factor [Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF], what is the air temperature will it have.

In [15]:
x = df[['Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]','Machine failure','TWF','HDF','PWF','OSF','RNF']]
x

Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  \
0                       308.6                    1551         42.8   
1                       308.7                    1408         46.3   
2                       308.5                    1498         49.4   
3                       308.6                    1433         39.5   
4                       308.7                    1408         40.0   
...                       ...                     ...          ...   
9995                    308.4                    1604         29.5   
9996                    308.4                    1632         31.8   
9997                    308.6                    1645         33.4   
9998                    308.7                    1408         48.5   
9999                    308.7                    1500         40.2   

      Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  
0                   0                0    0    0    0    0    0  
1                   3                0    0    0    0    0    0  
2                   5                0    0    0    0    0    0  
3                   7                0    0    0    0    0    0  
4                   9                0    0    0    0    0    0  
...               ...              ...  ...  ...  ...  ...  ...  
9995               14                0    0    0    0    0    0  
9996               17                0    0    0    0    0    0  
9997               22                0    0    0    0    0    0  
9998               25                0    0    0    0    0    0  
9999               30                0    0    0    0    0    0  

[10000 rows x 10 columns]

In [17]:
y = df[['Air temperature [K]']]
y

Air temperature [K]
0                   298.1
1                   298.2
2                   298.1
3                   298.2
4                   298.2
...                   ...
9995                298.8
9996                298.9
9997                299.0
9998                299.0
9999                299.0

[10000 rows x 1 columns]

In [18]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()

In [19]:
linear.fit(x,y)

LinearRegression()

In [20]:
linear.intercept_  # value of c

array([-64.20013022])

In [22]:
linear.coef_  # value of m

array([[ 1.17376384e+00,  1.90233804e-04,  2.67890316e-04,
         8.45451276e-05, -9.00858666e-02,  2.01756471e-01,
         1.77926496e+00,  1.41970075e-01, -4.04797285e-02,
        -5.72344840e-02]])

In [94]:
df.tail(20)

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
9980   9981     L57160    L                298.6                    308.4   
9981   9982     L57161    L                298.7                    308.5   
9982   9983     M24842    M                298.7                    308.4   
9983   9984     L57163    L                298.7                    308.4   
9984   9985     H39398    H                298.7                    308.4   
9985   9986     H39399    H                298.7                    308.5   
9986   9987     M24846    M                298.8                    308.6   
9987   9988     M24847    M                298.8                    308.6   
9988   9989     L57168    L                298.9                    308.6   
9989   9990     M24849    M                298.8                    308.5   
9990   9991     L57170    L                298.8                    308.5   
9991   9992     M24851    M                298.9                    308.4   
9992   9993     L57172    L                298.8                    308.4   
9993   9994     L57173    L                298.8                    308.4   
9994   9995     L57174    L                298.8                    308.3   
9995   9996     M24855    M                298.8                    308.4   
9996   9997     H39410    H                298.9                    308.4   
9997   9998     M24857    M                299.0                    308.6   
9998   9999     H39412    H                299.0                    308.7   
9999  10000     M24859    M                299.0                    308.7   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
9980                    1559         36.6              188                0   
9981                    1353         47.0              190                0   
9982                    1507         45.7              192                0   
9983                    1694         28.7              195                0   
9984                    1432         42.8              197                0   
9985                    1572         35.6              202                0   
9986                    1507         42.3              207                0   
9987                    1500         37.1              210                0   
9988                    1771         24.1              213                0   
9989                    1577         33.2                0                0   
9990                    1527         36.2                3                0   
9991                    1827         26.1                5                0   
9992                    1484         39.2                8                0   
9993                    1401         47.3               10                0   
9994                    1634         27.9               12                0   
9995                    1604         29.5               14                0   
9996                    1632         31.8               17                0   
9997                    1645         33.4               22                0   
9998                    1408         48.5               25                0   
9999                    1500         40.2               30                0   

      TWF  HDF  PWF  OSF  RNF  
9980    0    0    0    0    0  
9981    0    0    0    0    0  
9982    0    0    0    0    0  
9983    0    0    0    0    0  
9984    0    0    0    0    0  
9985    0    0    0    0    0  
9986    0    0    0    0    0  
9987    0    0    0    0    0  
9988    0    0    0    0    0  
9989    0    0    0    0    0  
9990    0    0    0    0    0  
9991    0    0    0    0    0  
9992    0    0    0    0    0  
9993    0    0    0    0    0  
9994    0    0    0    0    0  
9995    0    0    0    0    0  
9996    0    0    0    0    0  
9997    0    0    0    0    0  
9998    0    0    0    0    0  
9999    0    0    0    0    0

In [24]:
linear.predict([[308.6,1551,42.8,0,0,0,0,0,0,0]])

array([[298.32990779]])

In [25]:
linear.score(x,y)

0.7756660136661062

In [82]:
df1 = df[df['Machine failure']==1]

In [96]:
df1.tail(20)

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
9016  9017     L56196    L                297.3                    308.2   
9018  9019     L56198    L                297.3                    308.1   
9084  9085     L56264    L                297.2                    307.9   
9174  9175     L56354    L                297.8                    308.9   
9175  9176     L56355    L                297.8                    309.0   
9414  9415     L56594    L                298.1                    308.6   
9493  9494     L56673    L                299.1                    309.8   
9576  9577     L56756    L                299.6                    310.7   
9613  9614     L56793    L                299.0                    310.2   
9653  9654     L56833    L                299.0                    309.9   
9654  9655     L56834    L                299.1                    310.0   
9659  9660     L56839    L                298.9                    309.8   
9663  9664     L56843    L                299.1                    310.1   
9664  9665     L56844    L                299.1                    310.2   
9667  9668     L56847    L                299.2                    310.3   
9758  9759     L56938    L                298.6                    309.8   
9764  9765     L56944    L                298.5                    309.5   
9822  9823     L57002    L                298.5                    309.4   
9830  9831     L57010    L                298.3                    309.3   
9974  9975     L57154    L                298.6                    308.2   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
9016                    1396         52.7              212                1   
9018                    1615         35.4              217                1   
9084                    1326         75.4              172                1   
9174                    1871         25.6              200                1   
9175                    1403         64.2                0                1   
9414                    1354         53.9              207                1   
9493                    1398         55.4              217                1   
9576                    1922         23.3              205                1   
9613                    1377         62.5               92                1   
9653                    1373         55.7              201                1   
9654                    1367         56.3              203                1   
9659                    1287         61.9              216                1   
9663                    1435         48.8              229                1   
9664                    1317         54.8              231                1   
9667                    1352         48.9              238                1   
9758                    2271         16.2              218                1   
9764                    1294         66.7               12                1   
9822                    1360         60.9              187                1   
9830                    1337         56.1              206                1   
9974                    1361         68.2              172                1   

      TWF  HDF  PWF  OSF  RNF  
9016    0    0    0    1    0  
9018    1    0    0    0    0  
9084    0    0    1    1    0  
9174    1    0    0    0    0  
9175    0    0    1    0    0  
9414    0    0    0    1    0  
9493    0    0    0    1    0  
9576    1    0    0    0    0  
9613    0    0    1    0    0  
9653    0    0    0    1    0  
9654    0    0    0    1    0  
9659    0    0    0    1    0  
9663    0    0    0    1    0  
9664    0    0    0    1    0  
9667    0    0    0    1    0  
9758    1    0    0    0    0  
9764    0    0    1    0    0  
9822    0    0    0    1    0  
9830    0    0    0    1    0  
9974    0    0    1    1    0

In [84]:
# Test 1
linear.predict([[309.1,2861,4.6,143,1,0,0,1,0,0]])

array([[299.21973674]])

In [85]:
# Test 2
linear.predict([[308.1,1412,52.3,218,1,0,0,0,1,0]])

array([[297.60699357]])

In [88]:
# Test 3
linear.predict([[309.0,1741,28.0,21,0,0,0,0,0,0]])

array([[298.83336841]])

In [89]:
# Test 4
linear.predict([[308.2,1282,60.7,216,1,0,0,0,1,0]])

array([[297.70172075]])

In [93]:
# Test 5
linear.predict([[308.9,1455,41.3,208,1,1,0,0,0,0]])

array([[298.79262865]])

In [95]:
# Test 6
linear.predict([[308.4,1507,45.7,192,0,0,0,0,0,0]])

array([[298.10379428]])

In [97]:
# Test 7
linear.predict([[310.3,1352,48.9,238,1,0,0,0,1,0]])

array([[300.17864006]])

In [ ]:
# Test 8
linear.predict([[309.0,1741,28.0,21,0,0,0,0,0,0]])

In [98]:
# Test 9
linear.predict([[309.5,1294,66.7,12,1,0,0,1,0,0]])

array([[299.39670648]])

In [90]:
# Test 10
linear.predict([[308.6,1558,42.4,14,0,0,0,0,0,0]])

array([[298.3323159]])

In [99]:
# Model Accuracy

linear.score(x,y)

0.7756660136661062

In [112]:
# Save model

file = 'linear_regression_PredictiveModel.sav'

pickle.dump(file, open(file,'wb'))

In [123]:
# Save Model 
filename = 'finalized_model.sav'
joblib.dump(linear, filename)

['finalized_model.sav']

In [125]:
# load the model from disk
loaded_model = joblib.load(filename)
loaded_model.score(x, y)

0.7756660136661062

In [122]:
loaded_model.predict([[308.6,1558,42.4,14,0,0,0,0,0,0]])

array([[298.3323159]])