In [1]:
# Importing Required library
import joblib
import logging
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
from sklearn.linear_model import LinearRegression

In [4]:
class predictModel:
    logging.basicConfig(filename='model.log', level=logging.DEBUG, format='%(asctime)s %(levelname)s %(message)s')
    def pandasProfiling(self,dataFrame):
        self.dataFrame = dataFrame
        pf = ProfileReport(dataFrame)
        pf.to_widgets()
        logging.info("Pandas Profiling Done...")
    def myAnalysis(self):
        logging.info('My Analysis of Data( AI4I 2020 Predictive Maintenance)')

        logging.info('There is 14 number of attributes in my dataset which consist many funtionality [inner or outter] of machine.There is 5 inner funtionality which is highly correlated to Machine failure.\nIf any funtionality among these 5 are failed, then Machine will failed definetly.\nThis dataset also consist type of machine i.e. High, Medium and Low which indicated the product quality.\nOur task is to find out, on certain point or consist certain output of these factor [Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF], what is the air temperature will it have.')
        
    def gettingIndependentAndDependentFeatures(self, dataFrame):
        self.dataFrame = dataFrame
        self.x =  self.dataFrame[['Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]','Machine failure','TWF','HDF','PWF','OSF','RNF']]
        self.y = self.dataFrame[['Air temperature [K]']]
        logging.info('Independent and Dependent Feature is created.. ')
        return self.x
    def createModel(self, dataFrame):
        self.linear = LinearRegression()
        (self.linear).fit(self.x,self.y)
        logging.info(str((self.linear).fit(self.x,self.y))+' Model Object is created....')
    def testModel(self,independentData):
        logging.info('Model Testing '+str((self.linear).predict([independentData])))
    def modelAccuracy(self):
        logging.info('Model Accuracy '+str((self.linear).score(self.x,self.y)))
    def modelSaving(self,fileName):
        self.fileName = fileName
        joblib.dump(self.linear, fileName)
        logging.info('Saving Model File..')
    def modelLoading(self):   
        loaded_model = joblib.load(self.fileName)
        logging.info('Loading Model File..')

In [5]:
modelObj = predictModel()
df = pd.read_csv('ai4i2020.csv')
modelObj.pandasProfiling(df)
modelObj.myAnalysis()
modelObj.gettingIndependentAndDependentFeatures(df)
modelObj.createModel(df)
modelObj.testModel([309.5,1294,66.7,12,1,0,0,1,0,0])
modelObj.modelAccuracy()
modelObj.modelSaving('modelCopy.sav')
modelObj.modelLoading()

In [84]:
# Test 1
linear.predict([[309.1,2861,4.6,143,1,0,0,1,0,0]])

array([[299.21973674]])

In [85]:
# Test 2
linear.predict([[308.1,1412,52.3,218,1,0,0,0,1,0]])

array([[297.60699357]])

In [88]:
# Test 3
linear.predict([[309.0,1741,28.0,21,0,0,0,0,0,0]])

array([[298.83336841]])

In [89]:
# Test 4
linear.predict([[308.2,1282,60.7,216,1,0,0,0,1,0]])

array([[297.70172075]])

In [93]:
# Test 5
linear.predict([[308.9,1455,41.3,208,1,1,0,0,0,0]])

array([[298.79262865]])

In [95]:
# Test 6
linear.predict([[308.4,1507,45.7,192,0,0,0,0,0,0]])

array([[298.10379428]])

In [97]:
# Test 7
linear.predict([[310.3,1352,48.9,238,1,0,0,0,1,0]])

array([[300.17864006]])

In [ ]:
# Test 8
linear.predict([[309.0,1741,28.0,21,0,0,0,0,0,0]])

In [98]:
# Test 9
linear.predict([[309.5,1294,66.7,12,1,0,0,1,0,0]])

array([[299.39670648]])

In [90]:
# Test 10
linear.predict([[308.6,1558,42.4,14,0,0,0,0,0,0]])

array([[298.3323159]])